var sides = [
          "Bacon & Cheddar Grits",
          "Dandelion Naan",
          "Blue Cheese Deviled Eggs",
          "Seared Cauliflower",
          "Blistered Shishito Peppers",
          "Massaman Curry Empanadas",
          "Sweet Pea Saffron Rice",
          "Fried 3 Sisters Cakes",
          "Mini Wonton Quiche",
          "Potatoes Au Gratin",
          "Brussel Sprout Gratin",
          "Lambas Bread",
          "Tater Salad",
          "Calamari",
          "Bilbo's Tea Cakes",
          "Parmesian Roasted Carrots",
          "Ninja Turtle Soup",
          ];

var mains = [
          "Venison Egg Rolls",
          "Achiote Carnitas Tacos",
          "Seared Scallops w/ Brown Butter Sauce",
          "Coconut-Miso Salmon Curry",
          "Okonomiyaki(Seafood Pancakes)",
          "Blanquette de Veau",
          "Yakitori",
          "Cioppino Stew",
          "Roast Suckling Pig",
          "Anticucho de Corazon",
          "Ceviche Mixto",
          "Spaghetti alla Puttanesca",
          "Porchetta Sandwich",
          "Lambas Bread",
          "Lamb Chops",
          "Pikachu Stew",
          "Seared Charizar",
          "Big Kahuna Burger",
          "The Old 96'er",
          ];

var desserts = [
          "Chocolate Fraisier",
          "Chocolate Roulade",
          "Coffee & Walnut Battenburg",
          "Paul Hollywood's Iced Fingers",
          "Tarte Au Citron",
          "Victoria Sponge",
          "Brioche Frangipane Apple Pudding",
          "Apple & Lemon Sandwich Cake",
          "Savarin with Chantilly Cream",
          "Marjolaine",
          "Dampfnudel",
          "Viennese Whirls",
          "Hazelnut Dacquoise",
          "More Lambas Bread",
          "Lava Cakes",
          "Turkish Delight",
          "Imagination Pie",
          "$5 Shake",
          ];
